
CREATE PROCEDURE  sproc_LibraryDB 

AS 

CREATE TABLE "LIB_USER" ( 
    "USER_ID" INTEGER (*,0) NOT NULL primary key, 
    "USER_FIRSTNAME" VARCHAR (20) NOT NULL, 
    "USER_LASTNAME" VARCHAR (20) NOT NULL, 
    "USER_PHONENUMBER" INTEGER (12) NOT NULL, 
    "USER_EMAIL" VARCHAR (30) NOT NULL, 
    "USER_TYPE" VARCHAR (6) NOT NULL, 
    "USER_STATUS" VARCHAR (1) NOT NULL, 
USING INDEX ENABLE 

); 

CREATE TABLE "LIB_BOOK" ( 
    "BOOK_ID" INTEGER (*,0) NOT NULL primary key, 
    "BOOK_ISBN" INTEGER (13) NOT NULL, 
    "BOOK_TITLE" VARCHAR (50) NOT NULL, 
    "BOOK_AUTHOR" VARCHAR (50) NOT NULL, 
    "BOOK_YOP" DATE NOT NULL, 
    "BOOK_PUBLISHER" VARCHAR (30) NOT NULL, 
USING INDEX ENABLE 

); 

CREATE TABLE "LIB_BOOKCOPY" ( 
    "BOOKCOPY_COPYNO_ID" INTEGER (*,0) NOT NULL primary key, 
    "BOOKCOPY_ID" INTEGER (*,0) NOT NULL ENABLE, 
    "BOOKCOPY_CONDITION" VARCHAR (100) NOT NULL ENABLE, 
    "BOOK_ID" integer FOREIGN KEY references "LIB_BOOK" ("BOOK_ID") 
USING INDEX ENABLE 

); 

CREATE TABLE "LIB_RESVERVATION" ( 
    "RESERVATION_ID" INTEGER (*,0) NOT NULL primary key, 
    "RESERVATION_USERID" INTEGER (*,0) NOT NULL, 
    "RESERVATION_DATE" DATE NOT NULL, 
    "RESERVATION_COPYNO_ID" INTEGER (*,0) NOT NULL, 
    "USER_ID" INTEGER FOREIGN KEY references "LIB_USER" ("USER_ID") 
USING INDEX ENABLE 

); 
 
CREATE TABLE "LIB_LOAN" ( 
    "LOAN_ID" INTEGER (*,0) NOT NULL ENABLE primary key,  
    "LOAN_COPYNOID" INTEGER (*,0) NOT NULL ENABLE,  
    "LOAN_DETAILS" VARCHAR (100) NOT NULL ENABLE, 
    "LOAN_ISSUEDATE" DATE NOT NULL ENABLE, 
    "LOAN_RETURNDATE" DATE NOT NULL ENABLE, 
    "LOAN_RENEWALDATE" DATE NOT NULL ENABLE, 
    "LOAN_FINESTATUS" VARCHAR (1) NOT NULL ENABLE, 
    "LOAN_FINEAMOUNT" DECIMAL NOT NULL ENABLE,
    "USER_ID" INTEGER FOREIGN KEY references "LIB_USER" ("USER_ID") 
USING INDEX ENABLE 

); 

CREATE TABLE "LIB_OFFENCE" ( 
    "OFFENCE_ID" VARCHAR(1) NOT NULL primary key, 
    "OFFENCE_USERID" INTEGER (*,0) NOT NULL, 
    "OFFENCE_DATE" DATE NOT NULL, 
    "OFFENCE_DETAILS" VARCHAR (100) NOT NULL ENABLE, 
    "USER_ID" INTEGER FOREIGN KEY REFERENCES "LIB_USER" ("USER_ID") 
USING INDEX ENABLE 
); 
    
/
